//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Begonia.Toyota.WebSite.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class a_used_car_info_img
    {
        public int Id { get; set; }
        public string img { get; set; }
        public int a_used_car_info_id { get; set; }
        public int orderfield { get; set; }
    }
}
