//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Begonia.Toyota.WebSite.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class a_used_car_info
    {
        public int Id { get; set; }
        public string type { get; set; }
        public string product_type_id { get; set; }
        public string list_img { get; set; }
        public string number { get; set; }
        public string engine_id { get; set; }
        public string tool { get; set; }
        public string tonnes { get; set; }
        public string length { get; set; }
        public string engine_number { get; set; }
        public string car_number { get; set; }
        public string years { get; set; }
        public string used_hours { get; set; }
        public string price { get; set; }
        public string contact_person { get; set; }
        public string contact_method { get; set; }
        public int orderfield { get; set; }
        public bool status { get; set; }
        public System.DateTime create_time { get; set; }
        public string create_id { get; set; }
    }
}
