//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Begonia.Toyota.WebSite.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact_catalog_manager
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> answer_date { get; set; }
        public string service_units { get; set; }
        public string tel { get; set; }
        public string address { get; set; }
        public string have_brand { get; set; }
        public string want_catalog { get; set; }
        public string remark { get; set; }
        public string answer { get; set; }
        public System.DateTime create_date { get; set; }
        public string create_id { get; set; }
        public string answer_name { get; set; }
        public int status { get; set; }
    }
}
