//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Begonia.Toyota.WebSite.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class fixed_data2
    {
        public string Id { get; set; }
        public string type { get; set; }
        public string c1 { get; set; }
        public string c2 { get; set; }
        public System.DateTime create_date { get; set; }
        public string create_id { get; set; }
    }
}
