//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Begonia.Toyota.WebSite.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class index_banner
    {
        public int Id { get; set; }
        public string banner_title { get; set; }
        public string banner_intro { get; set; }
        public string btn_url { get; set; }
        public string img { get; set; }
        public int orderfield { get; set; }
        public bool status { get; set; }
        public System.DateTime create_time { get; set; }
        public string create_id { get; set; }
    }
}
