//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Begonia.Toyota.WebSite.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class info_location
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string location { get; set; }
        public string address { get; set; }
        public string tel { get; set; }
        public string fax { get; set; }
        public int orderfield { get; set; }
        public bool status { get; set; }
        public System.DateTime create_time { get; set; }
        public string create_id { get; set; }
    }
}
