//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Begonia.Toyota.WebSite.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_login
    {
        public int Id { get; set; }
        public string AccountId { get; set; }
        public string AccountName { get; set; }
        public string IP { get; set; }
        public bool LoginStatus { get; set; }
        public Nullable<System.DateTime> LoginTime { get; set; }
        public Nullable<System.DateTime> LogoutTime { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string FailReson { get; set; }
    }
}
