//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Begonia.Toyota.WebSite.DbContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class toyota_machineryEntities : DbContext
    {
        public toyota_machineryEntities()
            : base("name=toyota_machineryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<a_used_car_engine> a_used_car_engine { get; set; }
        public DbSet<a_used_car_info> a_used_car_info { get; set; }
        public DbSet<a_used_car_info_img> a_used_car_info_img { get; set; }
        public DbSet<contact_catalog_manager> contact_catalog_manager { get; set; }
        public DbSet<contact_us_manager> contact_us_manager { get; set; }
        public DbSet<fixed_data> fixed_data { get; set; }
        public DbSet<fixed_data2> fixed_data2 { get; set; }
        public DbSet<index_banner> index_banner { get; set; }
        public DbSet<index_video> index_video { get; set; }
        public DbSet<info_location> info_location { get; set; }
        public DbSet<info_news> info_news { get; set; }
        public DbSet<info_prize> info_prize { get; set; }
        public DbSet<log_login> log_login { get; set; }
        public DbSet<log_news> log_news { get; set; }
        public DbSet<product_accessories> product_accessories { get; set; }
        public DbSet<product_info> product_info { get; set; }
        public DbSet<product_info_accessories_list> product_info_accessories_list { get; set; }
        public DbSet<product_info_spc_image> product_info_spc_image { get; set; }
        public DbSet<question_and_answer> question_and_answer { get; set; }
        public DbSet<T_Account> T_Account { get; set; }
        public DbSet<T_Account_Permission_Mapping> T_Account_Permission_Mapping { get; set; }
        public DbSet<T_Permission> T_Permission { get; set; }
    }
}
