//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Begonia.Toyota.WebSite.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_info_spc_image
    {
        public int Id { get; set; }
        public string img { get; set; }
        public string intro { get; set; }
        public int orderfield { get; set; }
        public int product_id { get; set; }
    }
}
