//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Begonia.Toyota.WebSite.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_info
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string sub_title { get; set; }
        public string product_type_id { get; set; }
        public string engine_id { get; set; }
        public string img { get; set; }
        public string banner { get; set; }
        public string overview_type { get; set; }
        public double overview_tonnes_start { get; set; }
        public double overview_tonnes_end { get; set; }
        public string overview_img { get; set; }
        public string overview_img_intro { get; set; }
        public string introduction { get; set; }
        public string detail_gas { get; set; }
        public string detail_diesel { get; set; }
        public string detail_electric { get; set; }
        public string detail_overlook_img { get; set; }
        public string detail_slide_img { get; set; }
        public string detail_engine_table { get; set; }
        public string detail_motor_battery_table { get; set; }
        public string meta_keywords { get; set; }
        public string meta_description { get; set; }
        public System.DateTime create_time { get; set; }
        public string create_id { get; set; }
        public bool status { get; set; }
        public int orderfield { get; set; }
        public Nullable<System.DateTime> on_shelf_date { get; set; }
        public string overview_title { get; set; }
        public string overview_intro { get; set; }
        public string logo { get; set; }
    }
}
