//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Begonia.Toyota.WebSite.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Account_Permission_Mapping
    {
        public string Id { get; set; }
        public string AccountId { get; set; }
        public string PermissionId { get; set; }
        public string CreateUserId { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
